### ISSUE TITLE
1.0.0.7 pkg only contains PSRR measurement

### ISSUE THREAD

**Issue by NI-adamlin** [NI-Measurement-Plug-Ins/pmic-labview#47]
I downloaded version 1.0.0.7 and installed it on InstrumentStudio 2024Q4, but it looked like it only contains the PSRR measurement.

<img width="586" alt="圖片" src="https://github.com/user-attachments/assets/e6477f98-675b-466f-9479-e6744749e200">

**Comment by Upatel-NI** [comment]
I have updated 1.0.0.7 now all the measurements are present in 1.0.0.7 package.
